### ISSUE TITLE
能否添加导出标注图片的功能呢

### ISSUE THREAD

**Issue by gclm** [rachelcao277/LabelImage#7]
首先感谢作者的辛勤付出，项目很棒，但是发现他好像没有导出标注图片的功能。目前的快照只是导出原图片而不是导出标注图片
![image](https://user-images.githubusercontent.com/27618687/132839579-0fb9c36d-578a-4c8d-a3fd-098cf729cd9d.png)

![image](https://user-images.githubusercontent.com/27618687/132839556-a5a9544b-8ce1-453b-ad8e-4e441d38fdfa.png)

**Comment by rachelcao277** [comment]
快照导出图片标注功能已增加；
tips：如需将标签名称一起导出需开启显示标注结果功能

**Comment by rachelcao277** [comment]
快照导出图片标注功能已增加；
tips：如需将标签名称一起导出需开启显示标注结果功能
